# Generated by Django 5.2 on 2025-05-01 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='crated',
            new_name='created',
        ),
    ]
