# Generated by Django 5.2 on 2025-05-01 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_crated_services_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
