# Generated by Django 5.2 on 2025-05-01 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_rename_services_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created'], 'verbose_name': 'servicio', 'verbose_name_plural': 'servicios'},
        ),
    ]
